import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "tailwind.css";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

const groteskSpace = localFont({
  src: [
    {
      path: "./fonts/SpaceGrotesk-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/SpaceGrotesk-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/SpaceGrotesk-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/SpaceGrotesk-Bold.woff2",
      weight: "600",
      style: "normal",
    },
  ],
  variable: "--font-grotesk",
});

export const metadata: Metadata = {
  title: "MatchJobs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${inter.variable} ${groteskSpace.variable} bg-[--bg]`}>
        {children}
      </body>
    </html>
  );
}
