import type { Metadata } from "next";
import { Inter } from "next/font/google";
import 'tailwind.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MatchJobs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${inter.className} bg-[--bg]`}>{children}</body>
    </html>
  );
}
